// Generated by CoffeeScript 1.6.2
var getGamepad;

document.addEventListener('keydown', function(event) {
  var kbPressed;

  if (event.keyCode === 38) {
    window.controls.up = true;
  } else if (event.keyCode === 40) {
    window.controls.down = true;
  } else if (event.keyCode === 37) {
    window.controls.left = true;
  } else if (event.keyCode === 39) {
    window.controls.right = true;
  } else if (event.keyCode === 32) {
    window.controls.space = true;
  }
  kbPressed = true;
  return event.preventDefault();
});

document.addEventListener('keyup', function(event) {
  var kbPressed;

  if (event.keyCode === 38) {
    window.controls.up = false;
  } else if (event.keyCode === 40) {
    window.controls.down = false;
  } else if (event.keyCode === 37) {
    window.controls.left = false;
  } else if (event.keyCode === 39) {
    window.controls.right = false;
  } else if (event.keyCode === 32) {
    window.controls.space = false;
  }
  kbPressed = false;
  return event.preventDefault();
});

getGamepad = function() {
  var gamepad, gamepadIcon;

  if (!kbPressed) {
    gamepad = navigator.webkitGetGamepads && navigator.webkitGetGamepads()[0] || navigator.mozGetGamepads && navigator.mozGetGamepads()[0];
    gamepadIcon = document.querySelector('.icon-gamepad');
    if (gamepad !== void 0) {
      window.controls.up = gamepad.buttons[12] || gamepad.axes[1] <= -.5 || gamepad.axes[3] <= -.5 ? true : false;
      window.controls.down = gamepad.buttons[13] || gamepad.axes[1] >= .5 || gamepad.axes[3] >= .5 ? true : false;
      window.controls.left = gamepad.buttons[14] || gamepad.axes[0] <= -.5 || gamepad.axes[2] <= -.5 ? true : false;
      window.controls.right = gamepad.buttons[15] || gamepad.axes[0] >= .5 || gamepad.axes[2] >= .5 ? true : false;
      window.controls.space = gamepad.buttons[0] ? true : false;
      return gamepadIcon.className = 'icon-gamepad';
    } else {
      return gamepadIcon.className = 'icon-gamepad muted';
    }
  }
};
