// Generated by CoffeeScript 1.6.2
var canvas, ctx, fps, fpsHolder, frame, getIndexById, kbPressed, mainLoop, map, mlCalled, players;

canvas = document.querySelector('canvas');

ctx = canvas.getContext('2d');

frame = 0;

kbPressed = false;

players = [];

map = {};

mlCalled = new Date().getTime();

fps = 0;

fpsHolder = document.querySelector('.fps');

window.controls = {
  up: false,
  down: false,
  left: false,
  right: false,
  space: false
};

document.addEventListener('DOMContentLoaded', function() {
  var requestAnimationFrame;

  map = new Map;
  map.loadMap();
  requestAnimationFrame = function() {
    return window.requestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || window.mozRequestAnimationFrame || window.webkitRequestAnimationFrame || function(callback) {
      return window.setTimeout(callback, 1000 / 60);
    };
  };
  return mainLoop();
});

mainLoop = function() {
  var delta, player, _fn, _i, _len;

  delta = (new Date().getTime() - mlCalled) / 1000;
  mlCalled = new Date().getTime();
  fps = 1 / delta;
  fpsHolder.innerHTML = Math.floor(fps);
  frame++;
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  map.resize();
  if (map.map !== void 0) {
    map.draw();
  }
  _fn = function() {
    return player.drawHealthBar();
  };
  for (_i = 0, _len = players.length; _i < _len; _i++) {
    player = players[_i];
    _fn();
  }
  return requestAnimationFrame(mainLoop);
};

getIndexById = function(id) {
  var i;

  i = 0;
  while (id !== players[i].id) {
    i++;
  }
  return i;
};
